# NumPy & Pandas Basics

## Objective
This notebook covers 1D/2D NumPy array operations and basic Pandas dataset inspection.


---

## 1. NumPy 1D Arrays

This section covers creating 1D arrays, basic math, sorting, and filtering.

In [1]:
import numpy as np

ratings_arr  = np.array([8.8, 7.9, 9.0, 7.8, 8.6, 8.5, 8.4, 8.4, 8.0, 8.5])
popularity_arr = np.array([29.1, 185.0, 25.5, 41.5, 32.0, 52.3, 163.0, 60.0, 89.4, 110.5])

print("── NumPy 1D Array ──")
print(f"  Shape      : {ratings_arr.shape}")
print(f"  Dtype      : {ratings_arr.dtype}")
print(f"  Array      : {ratings_arr}")
print(f"  Sum        : {ratings_arr.sum():.2f}")
print(f"  Mean       : {ratings_arr.mean():.4f}")
print(f"  Std Dev    : {ratings_arr.std():.4f}")
print(f"  Min / Max  : {ratings_arr.min()} / {ratings_arr.max()}")
print(f"  Median     : {np.median(ratings_arr)}")
print(f"  Percentile 25/75: {np.percentile(ratings_arr, 25)} / {np.percentile(ratings_arr, 75)}")

print("\n── Array Arithmetic ──")
print(f"  ratings * 10   : {ratings_arr * 10}")
print(f"  ratings + 0.2  : {(ratings_arr + 0.2).round(1)}")
print(f"  ratings > 8.5  : {ratings_arr > 8.5}")
print(f"  Filtered ≥8.5  : {ratings_arr[ratings_arr >= 8.5]}")

mask = popularity_arr > 100
print(f"\n  Popularity > 100 mask  : {mask}")
print(f"  Ratings of those movies: {ratings_arr[mask]}")

── NumPy 1D Array ──
  Shape      : (10,)
  Dtype      : float64
  Array      : [8.8 7.9 9.  7.8 8.6 8.5 8.4 8.4 8.  8.5]
  Sum        : 83.90
  Mean       : 8.3900
  Std Dev    : 0.3673
  Min / Max  : 7.8 / 9.0
  Median     : 8.45
  Percentile 25/75: 8.1 / 8.575

── Array Arithmetic ──
  ratings * 10   : [88. 79. 90. 78. 86. 85. 84. 84. 80. 85.]
  ratings + 0.2  : [9.  8.1 9.2 8.  8.8 8.7 8.6 8.6 8.2 8.7]
  ratings > 8.5  : [ True False  True False  True False False False False False]
  Filtered ≥8.5  : [8.8 9.  8.6 8.5 8.5]

  Popularity > 100 mask  : [False  True False False False False  True False False  True]
  Ratings of those movies: [7.9 8.4 8.5]


---

## 2. NumPy 2D Arrays

This section covers stacking vectors, axes operations, reshaping, and stacking.

In [2]:
np.random.seed(42)
data_2d = np.column_stack([
    ratings_arr,
    popularity_arr / popularity_arr.max(),
    (np.array([2010,2009,2008,1997,2014,2019,2019,2019,2021,2023]) - 1990) / 35
])

print("── 2D Array ──")
print(f"  Shape         : {data_2d.shape}")
print(f"  Array:\n{data_2d.round(3)}")

print("\n── Row / Column operations ──")
print(f"  Mean per feature (col) : {data_2d.mean(axis=0).round(4)}")
print(f"  Mean per movie   (row) : {data_2d.mean(axis=1).round(4)}")
print(f"  Max per feature        : {data_2d.max(axis=0).round(4)}")

print(f"\n  Transposed shape       : {data_2d.T.shape}")
flat = data_2d.flatten()
print(f"  Flattened shape        : {flat.shape}")
restored = flat.reshape(10, 3)
print(f"  Restored shape         : {restored.shape}")

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(f"\n  vstack:\n{np.vstack([a,b])}")
print(f"  hstack:\n{np.hstack([a,b])}")

── 2D Array ──
  Shape         : (10, 3)
  Array:
[[8.8   0.157 0.571]
 [7.9   1.    0.543]
 [9.    0.138 0.514]
 [7.8   0.224 0.2  ]
 [8.6   0.173 0.686]
 [8.5   0.283 0.829]
 [8.4   0.881 0.829]
 [8.4   0.324 0.829]
 [8.    0.483 0.886]
 [8.5   0.597 0.943]]

── Row / Column operations ──
  Mean per feature (col) : [8.39   0.4261 0.6829]
  Mean per movie   (row) : [3.1762 3.1476 3.2174 2.7414 3.1529 3.2038 3.3699 3.1843 3.123  3.3467]
  Max per feature        : [9.     1.     0.9429]

  Transposed shape       : (3, 10)
  Flattened shape        : (30,)
  Restored shape         : (10, 3)

  vstack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
  hstack:
[[1 2 5 6]
 [3 4 7 8]]


---

## 3. Pandas Introduction

This section loads the dataset and explores its basic information.

In [3]:
import pandas as pd

np.random.seed(42)
n = 5000
GENRES = ['Action','Comedy','Drama','Horror','Thriller','Romance','Sci-Fi','Animation','Documentary','Fantasy']
LANGS  = ['en','fr','es','de','ja','hi','ko','pt','zh','it']
OVERVIEWS = [
    'A hero embarks on a dangerous journey to save the world.',
    'Two strangers meet and fall in love against all odds.',
    'A detective unravels a conspiracy in a futuristic city.',
    'An animated tale of friendship, courage and sacrifice.',
    'Aliens invade Earth and only one team can stop them.',
    'A young wizard discovers their true powers at school.',
    'A family torn apart by war seeks reunion across borders.',
    'Corporate espionage leads to a thrilling chase thriller.',
    'Space explorers find a mysterious signal from deep space.',
    'A comedy of errors involving mistaken identity.',
]

df = pd.DataFrame({
    'id':          range(1, n+1),
    'title':       [f'Movie {i:05d}' for i in range(1, n+1)],
    'genres':      [', '.join(np.random.choice(GENRES, np.random.randint(1,4), replace=False)) for _ in range(n)],
    'overview':    [np.random.choice(OVERVIEWS) for _ in range(n)],
    'popularity':  np.abs(np.random.normal(20, 40, n)).round(2),
    'vote_average':np.random.uniform(2.0, 9.8, n).round(1),
    'vote_count':  np.random.randint(0, 15000, n),
    'release_date':pd.date_range('1960-01-01', periods=n, freq='4D').astype(str),
    'revenue':     (np.abs(np.random.exponential(3e7, n))).astype(int),
    'runtime':     np.random.randint(60, 220, n),
    'original_language': np.random.choice(LANGS, n),
    'keywords':    ['adventure hero journey magic' for _ in range(n)],
    'status':      np.random.choice(['Released','Post Production','In Production','Planned'], n,
                                     p=[0.85,0.08,0.05,0.02]),
})

df.loc[np.random.choice(df.index, 400, replace=False), 'overview'] = np.nan
df.loc[np.random.choice(df.index, 200, replace=False), 'runtime']  = np.nan
df.loc[np.random.choice(df.index, 300, replace=False), 'revenue']  = 0

print(f"Dataset Shape : {df.shape}")
print(f"Columns       : {list(df.columns)}\n")

print("── Column Data Types ──")
print(df.dtypes)

print("\n── Numerical Summary ──")
print(df.describe().round(2))

missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)
missing_df = pd.DataFrame({'Missing Count': missing, 'Missing %': missing_pct})
missing_df = missing_df[missing_df['Missing Count'] > 0].sort_values('Missing %', ascending=False)
print("\n── Missing Values Summary ──")
print(missing_df)

print("\n── First 5 Rows ──")
df.head()

Dataset Shape : (5000, 13)
Columns       : ['id', 'title', 'genres', 'overview', 'popularity', 'vote_average', 'vote_count', 'release_date', 'revenue', 'runtime', 'original_language', 'keywords', 'status']

── Column Data Types ──
id                     int64
title                 object
genres                object
overview              object
popularity           float64
vote_average         float64
vote_count             int32
release_date          object
revenue                int32
runtime              float64
original_language     object
keywords              object
status                object
dtype: object

── Numerical Summary ──
            id  popularity  vote_average  vote_count       revenue  runtime
count  5000.00     5000.00       5000.00     5000.00  5.000000e+03  4800.00
mean   2500.50       35.06          5.92     7490.14  2.846485e+07   139.94
std    1443.52       26.38          2.24     4334.62  2.905544e+07    46.42
min       1.00        0.02          2.00        0

,id,title,genres,overview,popularity,vote_average,vote_count,release_date,revenue,runtime,original_language,keywords,status
0,1,Movie 00001,"Romance, Action, Fantasy",Corporate espionage leads to a thrilling chase...,53.29,7.9,11378,1960-01-01,10232040,186.0,hi,adventure hero journey magic,Released
1,2,Movie 00002,Action,Space explorers find a mysterious signal from ...,4.71,9.6,12665,1960-01-05,34616340,128.0,zh,adventure hero journey magic,Post Production
2,3,Movie 00003,"Sci-Fi, Drama",NaN,26.64,5.4,4192,1960-01-09,51237039,150.0,hi,adventure hero journey magic,Released
3,4,Movie 00004,"Comedy, Romance, Thriller",Corporate espionage leads to a thrilling chase...,56.93,2.6,6821,1960-01-13,16045701,61.0,de,adventure hero journey magic,Released
4,5,Movie 00005,"Fantasy, Drama, Animation",NaN,16.94,7.4,9351,1960-01-17,11617053,199.0,en,adventure hero journey magic,Released
